namespace: pichincha
name: sre
version: 1.0.7
readme: README.md
authors:
- SRE <sre@pichincha.com>
description: 'Esta colleción se encarga de la automatización de tareas de monitoreo/readiness para Servicios, Application pools, Servicios iis y aplicaciones Web basadas en plataformas Windows Server.'
license:
- GPL-2.0-or-later
tags:
  - sre
  - readiness
dependencies:
  community.windows: '>=2.3.0'
  ansible.windows: '>=2.7.0'
  community.general: '>=10.4.0'
repository: http://example.com/repository
homepage: http://example.com
issues: http://example.com/issue/tracker
build_ignore: []
