---
- name: Debug de impresion de prueba de collection 'pichincha.sre'
  ansible.builtin.debug:
    msg: "Ejecutando el Role de readiness para Wintel en {{ inventory_hostname }}"
  delegate_to: localhost

- name: Debug de Application Pools enviados a la collcetion 'pichincha.sre'
  ansible.builtin.debug:
    msg: "El nombre del Application Pool es {{ win_app_pools }}"
  delegate_to: localhost

- name: Debug de Servicios enviados a la collcetion 'pichincha.sre'
  ansible.builtin.debug:
    msg: "El nombre del servicio es {{ win_services }}"
  delegate_to: localhost

- name: Debug de Servicios enviados a la collcetion 'pichincha.sre'
  ansible.builtin.debug:
    msg: "La url de dynatrace es {{ url_monitoreo }}"
  delegate_to: localhost

- name: Importar tareas para validar IIS.
  ansible.builtin.import_tasks: wintel_readiness_validar_iis.yml
  run_once: true

- name: Importar tareas para validar IIS Pools
  ansible.builtin.import_tasks: wintel_readiness_pool_iis.yml
  run_once: true
