# tasks file for webteller_readiness_validar_iis
- name: Bloque para verificar estado de IIS.
  block:
    - name: Verificando estado de los servicios IIS.
      ansible.windows.win_command: iisreset.exe /STATUS
      register: wintel_readiness_iis_status
      failed_when: "'Stopped' in wintel_readiness_iis_status['stdout']"
      changed_when: false

    - name: Mostrar estado de los servicios IIS.
      ansible.builtin.debug:
        msg: >
          {{ wintel_readiness_iis_status['stdout_lines'] }}
  rescue:
    - name: Error en estado de servicios IIS.
      ansible.builtin.set_fact:
        wintel_readiness_error_message:
          '{{ wintel_readiness_error_message + ["Hay servicios de IIS detenidos en {{ inventory_hostname }}."] }}'
        wintel_readiness_error_flag: true
